<a href="https://colab.research.google.com/github/akipi-ro/b/blob/master/dip%E9%9B%86%E7%B4%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [141]:
# coding: utf-8
import numpy as np
import pandas as pd
import sklearn


x=pd.read_csv("train_x.csv")#説明
y=pd.read_csv("train_y.csv")#目的

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

#欠損値の処理

In [154]:
x=x.dropna(how='all',axis=1)#全て欠損値の列を削除

# x.isnull().sum()[x.isnull().sum()>=15853].sort_values()
x.isnull().sum()[x.isnull().sum()<=0].sort_values()#無欠損のデータを確認



#型の確認
na_columns = x.isnull().sum()[x.isnull().sum()>=15853].sort_values().index.tolist()#ゴミの型の確認
na_columns = x.isnull().sum()[x.isnull().sum()<=0].sort_values().index.tolist()#無欠損型の確認
x[na_columns].dtypes

x.describe()#代表値の確認

#欠損値の穴埋め
print([x.isnull().sum()>0])

[職場の様子               False
（紹介予定）入社後の雇用形態       True
勤務地固定               False
休日休暇(月曜日)           False
（派遣先）配属先部署　男女比　男     True
                    ...
勤務地　最寄駅1（駅名）        False
勤務地　最寄駅2（分）          True
給与/交通費　備考            True
残業なし                False
期間･時間　備考             True
Length: 127, dtype: bool]

ValueError: ignored

#Xの重複について

1.   重複をNoごとにまとめた

In [143]:
#print(x[x.duplicated()])#重複の確認　重なっているものを出す
# x.duplicated()　　　　　　　　　　　　#全てのデータを出し、true,Flaseで出す
#print(x.duplicated().value_counts())#重複した数を示す


# print(x.drop_duplicates())#重複けした後表示用
x=x.drop_duplicates()#.reset_index()#重複の決定　インデックスは振ってない
x.describe()

              職場の様子  （紹介予定）入社後の雇用形態  ...  勤務地　最寄駅2（分）          残業なし
count  11124.000000     1747.000000  ...  5140.000000  11124.000000
mean       2.946422        1.310246  ...     7.614202      0.735707
std        0.306961        0.500771  ...     4.571798      0.440976
min        2.000000        0.000000  ...     1.000000      0.000000
25%        3.000000        1.000000  ...     5.000000      0.000000
50%        3.000000        1.000000  ...     7.000000      1.000000
75%        3.000000        2.000000  ...    10.000000      1.000000
max        4.000000        2.000000  ...    46.000000      1.000000

[8 rows x 95 columns]

In [144]:
y=y.drop_duplicates()#
y

           お仕事No.    応募数 合計
0      2203566799  1.945910
1      2203546900  3.951244
2      2203546900  3.295837
3      2203545344  3.970292
4      2203545344  3.784190
...           ...       ...
15847  5203543470  0.000000
15848  5903549258  0.000000
15849  5903542254  0.000000
15851  5203533881  0.693147
15852  5203544938  0.000000

[11687 rows x 2 columns]

#yの重複について

1.   重複を集約し、平均化

2.   ただし応募数によってxより行数が少なくなる

In [145]:
y.isnull().sum()
y
print(y[y.duplicated()])
y

Empty DataFrame
Columns: [お仕事No., 応募数 合計]
Index: []

           お仕事No.    応募数 合計
0      2203566799  1.945910
1      2203546900  3.951244
2      2203546900  3.295837
3      2203545344  3.970292
4      2203545344  3.784190
...           ...       ...
15847  5203543470  0.000000
15848  5903549258  0.000000
15849  5903542254  0.000000
15851  5203533881  0.693147
15852  5203544938  0.000000

[11687 rows x 2 columns]

In [146]:
y=y.groupby("お仕事No.").agg({"応募数 合計":"mean"})　#集約と平均化
# y=y.groupby("お仕事No.")
# y.head()

y.reset_index(inplace=True)
y.colums =["お仕事No.","応募数　合計"]
y


print(y.duplicated().value_counts())
y

False    9671
dtype: int64

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

          お仕事No.    応募数 合計
0     1103518123  0.000000
1     1103521165  0.549306
2     1103523272  0.000000
3     1103528902  1.242453
4     1103529507  0.000000
...          ...       ...
9666  8403548442  0.000000
9667  8403555211  0.693147
9668  8403559095  0.000000
9669  8403560782  0.693147
9670  8403568835  0.000000

[9671 rows x 2 columns]

In [147]:
#xデータの確認
x.describe()
# y.describe()

              職場の様子  （紹介予定）入社後の雇用形態  ...  勤務地　最寄駅2（分）          残業なし
count  11124.000000     1747.000000  ...  5140.000000  11124.000000
mean       2.946422        1.310246  ...     7.614202      0.735707
std        0.306961        0.500771  ...     4.571798      0.440976
min        2.000000        0.000000  ...     1.000000      0.000000
25%        3.000000        1.000000  ...     5.000000      0.000000
50%        3.000000        1.000000  ...     7.000000      1.000000
75%        3.000000        2.000000  ...    10.000000      1.000000
max        4.000000        2.000000  ...    46.000000      1.000000

[8 rows x 95 columns]

In [152]:
x

       職場の様子  （紹介予定）入社後の雇用形態  ...  残業なし                      期間･時間　備考
0          3             NaN  ...     1  ◆開始日はご相談可能です！詳しくはお問い合わせください！
1          3             1.0  ...     1                           NaN
3          2             1.0  ...     0  ◆開始日はご相談可能です！詳しくはお問い合わせください！
5          3             1.0  ...     1                           NaN
6          3             NaN  ...     1                           NaN
...      ...             ...  ...   ...                           ...
15847      3             NaN  ...     1                           NaN
15848      2             NaN  ...     1                           NaN
15849      3             NaN  ...     1  ◆開始日はご相談可能です！詳しくはお問い合わせください！
15851      3             NaN  ...     0                           NaN
15852      3             NaN  ...     0                           NaN

[11124 rows x 127 columns]

#共通お仕事No以外の削除

In [157]:
A=set(x)&set(y)
print(A)
len(A)

{'お仕事No.'}

1

#配列変換

In [0]:
y_array=np.array(y)
x_array=np.array(x)

In [149]:

print(y_array.shape)
x_array.shape

(9671, 2)

(11124, 127)

#アルゴリズム構築

In [0]:
from sklearn.model_selection import train_test_split

In [151]:
x_train,x_test,y_train,y_test = train_test_split(x_array,y_array,test_size = 0.4,random_state =0)

ValueError: ignored

#結果出力

In [0]:
# =pd.DataFrame({"Id" : houseprice_assignment["お仕事No."],"SalePrice" : y2_pred})

In [0]:
.to_csv("Ans.csv",index=False)

#テスト

In [0]:
X_test=pd.read_csv("test_x.csv")#testの説明変数
X_test.isnull()